config/routes.rb
Rails.application.routes.draw do
  root to: "jobs#index"
  devise_for :companies, controllers: {
    sessions:      'companies/sessions',
    passwords:     'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  
  resources :jobs do
    post 'add' => 'likes#create'
  delete '/add' => 'likes#destroy' 
  resources :messages
  end
  
  resources :users do
    resources :memos
  end

  resources :companies 
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  

end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs
  has_many :messages
  
  
  
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :users, through: :likes
   def liked_by?(user)
    likes.where(user_id: user.id).exists?
   end
  has_many :users, through: :messages
  has_many :messages
  has_one :prefecture
  has_many :likes
  has_many :relationships
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :jikyu
    validates :period
    validates :number_of_people
    validates :contents
    validates :prefecture_id
    validates :working_hours
  end
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :job,optional: true
  belongs_to :user,optional: true
  belongs_to :company,optional: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]

    include ActiveHash::Associations
    has_many :jobs
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :follow, class_name: 'Company'
  belongs_to :job
  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :jobs
  has_many :mesaages
  has_many :memos
  has_many :likes, dependent: :destroy
  has_many :like_jobs, through: :likes, source: :job
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :company
  
  

  with_options presence: true do
    validates :nickname
    validates :birthday
    validates :first_name, format: { with:/\A[ぁ-んァ-ン一-龥]/}
    validates :last_name, format: { with:/\A[ぁ-んァ-ン一-龥]/}
    validates :first_name_kana, format: { with:/\A[ァ-ヶー－]+\z/}
    validates :last_name_kana, format:  { with:/\A[ァ-ヶー－]+\z/}
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  def index
    @job = Job.all
    
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
      if @job.save
        redirect_to root_path
      else
        render :new
      end

      
  end

  def show
    @job = Job.find(params[:id])
    @messages = Message.all
    @message = Message.new
    @messages = @job.messages.includes(:user)
    
    

      
    
  end

  def destroy
    job = Job.find(params[:id])
      if job.destroy
        redirect_to root_path
      else
        render :edit
      end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    job = Job.find(params[:id])
      if job.update(job_params)
        redirect_to job_path
      else
        render :edit
      end
  end


private
  def job_params
    params.require(:job).permit(:title, :jikyu, :number_of_people, :prefecture_id, :working_hours, :contents, :period, :image).merge(company_id: current_company.id)
  end

  
  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_job

    def create
      user = current_user
        @job = Job.find(params[:job_id])
        @jobs = Job.all
        @like = Like.create(user_id: current_user.id, job_id: params[:job_id])
        @likes = Like.where(job_id: params[:job_id])
        @like.save
        @job = @like.job
    end
    def destroy
        user = current_user
        @job = Job.find(params[:job_id])
        @job = Job.all
        @likes = Like.where(job_id: params[:job_id])
        like = Like.find_by(user_id: current_user.id, job_id: params[:job_id])
        like.delete
    end

     private
    def set_job
        @job = Job.find(params[:job_id])
    end

  

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController 
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @memo = Memo.new
    @user = current_user
    @memos = Memo.where(user_id: current_user).order(start_time: "desc", end_time: "desc")
  end

  def edit
  
  end

  def create
    memo = Memo.new(memos_params)
    if memo.user_id = current_user.id
      memo.save
        flash[:notice] = "シフトを記録しました"
         redirect_to memos_path
    else
      render :index
    end
  end

  def update
    if @memo.update(memos_params)
       flash[:notice] = "シフトを更新しました"
       redirect_to memos_path
    else
      render :edit
    end
  end

  def destroy
    @memo.destroy
    flash[:notice] = "シフトを削除しました"
    redirect_to memos_path
  end

  def ensure_correct_user
    @memo = Memo.find(params[:id])
      unless @memo.user == current_user
        redirect_to memos_path
      end
  end

  private
    def memos_params
      params.require(:memo).permit(:title,:custoer_id,:start_time,:end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper

  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<div class="main">
<%= form_with model: job, local: true do |f| %>
<div class="field">
  <%= f.label :title, "仕事の名称" %><br />
  <%= f.text_area :title %>
  </div>

  <div class="field">
  <%= f.label :contents, "仕事内容" %><br />
  <%= f.text_area :contents, class: :form＿text %>
  </div>

  <div class="field">
  <%= f.label :period, "期間" %><br />
  <%= f.text_field :period %>
  </div>

  <div class="field">
  <%= f.label :number_of_people, "募集人数" %><br />
  <%= f.text_field :number_of_people %>
  </div>

  <div class="field">
  <%= f.label :jikyu, "時給" %><br />
  <%= f.text_field :jikyu %>
  </div>

  <div class="field">
  <%= f.label :working_hours, "勤務時間" %><br />
  <%= f.text_field :working_hours %>
  </div>

  <div class="field">
  <%= f.label :prefecture_id, "住所" %><br />
  <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"prefecture-select"}) %>
  </div>

  <div class="field">
  <%= f.label :image, "仕事の画像" %><br />
  <%= f.file_field :image %>
  </div>

  <div class="action">
    <%= f.submit "保存する", class: :form＿btn %>
  </div>
<% end %>

</div>

app/views/jobs/_job.html.erb
<div class="card">
  <%=link_to image_tag(job.image.variant(resize: '150x150'), class: :card__img), job_path(job.id) %>
  <div class="card__body">
    <%= "仕事名" %>
    <%= link_to job.title, job_path(job.id), class: :card__title %>
    <p class="card__summary">
      <%= "時給" %>
      <%=  job.jikyu  %>円
    </p>
    <p class="card__summary">
      <%= "仕事内容" %>
      <%=  job.contents  %>
    </p>

  <%= link_to "by#{job.company.company_name}", company_path(job.company.id), method: :get, class: :card__user %>

  </div>
</div>

app/views/jobs/edit.html.erb
<div class="main">
  <div>
    <div>
      <h2>仕事情報編集</h2>
      <%= render partial: "form", locals: { job: @job } %>
    </div>
  </div>
</div> 

app/views/jobs/index.html.erb
<!DOCTYPE HTML>
<html>
<div class="main">
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.3.7/css/swiper.min.css">
    
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <title>Simple Job</title>
    </head>
    <body>
      
  
    <div class='contents'>
      <h2 class='service-title'>
        スキマ時間を有効活用
      </h2>
    
      <p class='service-explain'>
        誰でも簡単に出来る仕事をマッチングする
      </p>
      <p class='service-explain'>
        マッチングアプリです
      </p>
      <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
    </div>
      <div class="middle-content">

      <h3>仕事情報</h3>
       </div> 
      <%# <div class="card__wrapper"> %>
      
      <%# </div> %>
      <div class="swiper-container"> 
	        
	    <div class="swiper-wrapper">
	      	 
		    <div class="swiper-slide"><%= render partial: 'job', collection: @job = Job.first(4) %></div>
        <div data-swiper-parallax="-300">Slide 1</div>
		    <div class="swiper-slide"><%= render partial: 'job', collection: @job = Job.last(4) %></div>
        <div data-swiper-parallax="-300">Slide 2</div>
		    <%# <div class="swiper-slide">Slide 3</div> %>
        <%# <div data-swiper-parallax="-300">Slide 3</div> %>
		    <%# <div class="swiper-slide">Slide 4</div> %>
        <%# <div data-swiper-parallax="-300">Slide 4</div> %>

        <div class="swiper-button-prev"></div>
	      <div class="swiper-button-next"></div>
        
	   </div>
     </div>
      </div>
      
      
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/5.3.7/js/swiper.min.js"></script>
  <script>
    var mySwiper = new Swiper('.swiper-container', {
  arallax: true,
  speed: 3000,
  autoplay: {
    delay: 4000,
		stopOnLastSlide: false,
		disableOnInteraction: false,
		reverseDirection: false
	},
	navigation: {
		nextEl: '.swiper-button-next',
		prevEl: '.swiper-button-prev'
	},
	pagination: {
		el: '.swiper-pagination',
		type: 'bullets',
		clickable: true
	}
});
</script>
    <footer>
    </footer>
    </body>
</div>
</html>    

app/views/jobs/new.html.erb
<div class="main">
  <div>
    <div>
      <h2>新規仕事掲載</h2>
      <%= render partial: "form", locals: { job: @job } %>
    </div>
  </div>
</div> 

app/views/jobs/show.html.erb
<div class="main">
<div class="job-show">
  <div class="job-box">
  <h2 class="name">
    <%= @job.title %> 
    <h2>
  <div class='job-img-content'>
    <%= image_tag @job.image, class: "job-img" %>
  </div>

  <div class="job-explain-box">
    <span><%= "求人案内" %>
  </div>
  <table class="detail-table">
    <tbody>
      <tr>
        <th class="detail-item">時給</th>
        <td class="detail-value"><%= @job.jikyu %>円</td>
      </tr>
      <tr>
        <th class="detail-item">勤務先</th>
        <td class="detail-value"><%= @job.prefecture.name %></td>
      </tr>
      <tr>
        <th class="detail-item">勤務時間</th>
        <td class="detail-value"><%= @job.working_hours %></td>
      </tr>
      <tr>
        <th class="detail-item">就業期間</th>
        <td class="detail-value"><%= @job.period %></td>
      </tr>
      <tr>
        <th class="detail-item">募集人数</th>
        <td class="detail-value"><%= @job.number_of_people%>人</td>
      </tr>
      <tr>
        <th class="detail-item">業務内容</th>
        <td class="detail-value"><%= @job.contents%></td>
       </tr> 
    </tbody>
    </table>

    <% if company_signed_in? %>
    <%= link_to '掲載の編集',edit_job_path, method: :get, class: "job-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除',"#", method: :delete, class:'job-destroy' %>
    
    <% end %>
    
<%# <%= render partial:'relationships/follow_button', user: @user %>  
    <div class="container">
    <% if company_signed_in? %>
      <%= form_with(model: [@job, @message], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
        <% end %>
      <% elsif user_signed_in? %>
       <%= form_with(model: [@job, @message], local: true) do |form| %>
       <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
        
        <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
      </strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @messages %> 
        <% @messages.each do |message| %>
          <p>
            
              <strong><%= link_to "by#{message.user.nickname}",user_path(message.user.id) %>：</strong>
            
              
            
            <%= message.text %> 
          </p>
        <% end %>
      <% end %> 
      <% if user_signed_in? %>
     <div id="like-btn-<%= @job.id %>">
       <%= render 'likes/like', job: @job %>
    </div>
      <% else company_signed_in? %>
      <span class="fa fa-heart icon-size like-btn"></span>
      <%= Like.where(job_id: @job).count %>
      <% end %>
    </div>
  </div>
  
</div>
</div>    

app/views/likes/_like.html.erb
<% if job.liked_by?(current_user) %>
   <%= link_to(job_add_path(job), method: :delete, remote: true, id: :"like-button-#{job.id}") do %>
      <span class="fa fa-heart icon-size like-btn-unlike"></span>
      <%= Like.where(job_id: job).count %>
   <% end %>
<% else %>
   <%= link_to(job_add_path(job), method: :post, remote: true, id: :"like-button-#{job.id}") do %>
        <span class="fa fa-heart icon-size like-btn"></span>
         <%= Like.where(job_id: job).count %>
   <% end %>
<% end %>

app/views/likes/create.js.erb
$("#like-button").html("<%= j(render partial: 'likes/like', locals: {job: @job,jobs: @jobs, likes: @likes, like: @like}) %>");

app/views/likes/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'likes/like', locals: {job: @job,jobs: @jobs, likes: @likes, like: @like}) %>");

app/views/memos/index.html.erb
<div class="container-fluid">
	<h2 class="section-top"><span class="fas fa-dumbbell" aria-hidden="true"></span> シフト管理表
  </h2>
	<div class="col-md-3 col-sm-12 col-xs-12">
   <%= form_for (@memo) do |f| %>
     <div class="field row">
       <label for='title'>用件</label>
       <p><%= f.text_area :title%></p>
       <label for="start_time">勤務開始可能時間</label>
       <p><%= f.datetime_select :start_time%></p>
       <label for="end_time">勤務終了希望時間</label>
       <p><%= f.datetime_select :end_time%></p>
     </div>
     <div class="actions row">
       <%= f.submit class: "btn btn-sm btn-hachiss" %>
     </div>
   <% end %>
     </div>
 	   <div class="col-md-9 col-sm-12 col-xs-12">
		   <%= month_calendar events: @user.memos do |date, memos| %>
		   <%= date.day %>
		   <% memos.each do |memo| %>
		    <div>
		      <%= link_to memo.title, edit_memo_path(memo) %>
		    </div>
		    <% end %>
		    <% end %>
	     <table class="memo table table-bordered">
         <thead>
            <tr>
                <th>用件</th>
                <th>勤務開始可能時間</th>
                <th>勤務終了希望時間</th>
            </tr>
         </thead>
           <% @memos.each do |user| %>
             <tbody>
                 <tr>
                     <td><%= user.title%></td>
                     <td><%= user.start_time.strftime("%Y-%m-%d %H:%M")%></td>
                     <td><%= user.end_time.strftime("%Y-%m-%d %H:%M")%></td>
                     <td><%=link_to "編集" , edit_memo_path(user),:class=>"btn04"  %></td>
						<td><%=link_to "削除",memo_path(user) , method: :delete , data: {confirm:"削除しますか"} ,:class=>"btn03"%></td>
					</tr>
				</tbody>
			<% end %>
  		</table>
  		<%# <%= paginate @memos %> %>
 	</div>
</div>